version: '3.6'

services:
  fooocus:
    build:
      context: .
      dockerfile: Dockerfile-cuda
    ports:
     - "7865:7865"
    privileged: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
